version: 0.2
env:
  variables: {}
phases:
  pre_build:
    commands:
      - export RELEASE_IMAGE_URL="$DOCKER_IMAGE_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION"
  build:
    commands:
      - docker build --tag "$RELEASE_IMAGE_URL" .
      - sed -i '' "s/RELEASE_IMAGE_URL/$RELEASE_IMAGE_URL/" parameters/*.params.json
      - |
        cat <<EOF > outputProperties.json
        {
          "image": "$RELEASE_IMAGE_URL", 
          "version": "$CODEBUILD_RESOLVED_SOURCE_VERSION"
        }
        EOF
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker push "$RELEASE_IMAGE_URL"
artifacts:
  discard-paths: yes
  files:
    - "cloudformation.template.yml"
    - "outputProperties.json"
    - "parameters/*"
    - "integration-tests/integration.buildspec.yml"