AWSTemplateFormatVersion: "2010-09-09"
Description: Sandbox for testing log events, ok to delete after 5/24/2018
Resources:
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      RetentionInDays: 5
  GetItemLatencyMetric:
    Type: "AWS::Logs::MetricFilter"
    Properties: 
      FilterPattern: '{$.operation="GetItem"}'
      LogGroupName: !Ref LogGroup
      MetricTransformations:
        - MetricNamespace: !Ref AWS::StackName
          MetricName: GetItem_LatencyMS
          MetricValue: "$.latencyMS"
  GetItemLatencyAlarm: 
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      Namespace: !Ref AWS::StackName
      MetricName: GetItem_LatencyMS
      Statistic: Average
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 50
      Period: 10
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref AlarmTopic
  AlarmTopic: 
    Type: "AWS::SNS::Topic"
    Properties: {}

  
  #Shared
  EmailAlarmSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: email
      Endpoint: "prowe@sourceallies.com"
  TxtAlarmSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: sms
      Endpoint: "13098541649"