AWSTemplateFormatVersion: "2010-09-09"
Description: Pipeline for node-reference
Parameters:
  RepoToken:
    Type: String
    NoEcho: true
    Description: OAuth Token for the github repository
  PipelineAdminArn:
    Type: String
    Description: |
      ARN of a user or role that can administrate this pipeline.
      This can be obtained by running aws sts get-caller-identity --query='Arn' --output=text
Resources:
  PipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: "sts:AssumeRole"
              Principal:
                Service: "codebuild.amazonaws.com"
            - Effect: "Allow" 
              Action: "sts:AssumeRole"
              Principal:
                Service: "codepipeline.amazonaws.com"
            - Effect: "Allow" 
              Action: "sts:AssumeRole"
              Principal:
                Service: "cloudformation.amazonaws.com"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  ArtifactStorage:
    Type: "AWS::S3::Bucket"
  PipelineKey:
    Type: "AWS::KMS::Key"
    Properties:
      KeyPolicy:
        Version: "2012-10-17"
        Statement: 
          - Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal: 
              AWS: !Ref PipelineAdminArn
            Action: 
              - "kms:*"
            Resource: "*"
          - Sid: "Allow use of the key"
            Effect: "Allow"
            Principal: 
              AWS: !GetAtt PipelineRole.Arn
            Action: 
              - "kms:Decrypt"
            Resource: "*"
          - Sid: "Allow Encryption by everyone"
            Effect: "Allow"
            Principal: 
              AWS: "*"
            Action: 
              - "kms:Encrypt"
            Resource: "*"
            Condition:
              StringEquals:
                "kms:CallerAccount": !Ref "AWS::AccountId"
  PipelineKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-key"
      TargetKeyId: !Ref PipelineKey
  ArtifactStoragePolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref ArtifactStorage
      PolicyDocument:
        Statement:
          - Action: s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${ArtifactStorage}
              - !Sub arn:aws:s3:::${ArtifactStorage}/*
            Principal:
              AWS:
                - !GetAtt PipelineRole.Arn
  DockerRepo:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Action:
              - "ecr:*"
            Principal:
              AWS:
                - !GetAtt PipelineRole.Arn
  BuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - PipelineRole
    Properties:
      ServiceRole: !GetAtt PipelineRole.Arn
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:1.12.1
        EnvironmentVariables:
          - Name: DOCKER_IMAGE_URL
            Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${DockerRepo}"
      Artifacts:
        Type: CODEPIPELINE
  IntegrationTest:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - PipelineRole
    Properties:
      ServiceRole: !GetAtt PipelineRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: integration.buildspec.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:17.09.0
        EnvironmentVariables:
          - Name: BASE_URL
            Value: "https://prowe-products.dev.sourceallies.com/"
          - Name: CLIENT_ID
            Value: "4c8mmtv4fsrlomvt2k209u3fui"
          - Name: ENCRYPTED_CLIENT_SECRET
            Value: "AQICAHiZgD/jeR0oOREQtYJrh9wib6dOVY7T9VTN4zxzBZQ09gE53bazErDBAxwCkntFIQZuAAAAljCBkwYJKoZIhvcNAQcGoIGFMIGCAgEAMH0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+yeBckRCM5xy85sQAgEQgFCPKABigjlatrQ9uScjAyL9c5n0zEmComzaHnF6f354wmQfF4YwdHd+95/iTEB113oJnA3GMQ/dC0DUg2YC8MdBg+HGF4H83LcAJCfPCv87qg=="
          - Name: TOKEN_ENDPOINT
            Value: "https://proucts.auth.us-east-1.amazoncognito.com/oauth2/token"
      Artifacts:
        Type: CODEPIPELINE
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - BuildProject
    Properties:
      ArtifactStore:
        Type: "S3"
        Location: !Ref ArtifactStorage
      RoleArn: !GetAtt PipelineRole.Arn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
          - Name: Source
            ActionTypeId:
              Category: Source
              Provider: GitHub
              Owner: ThirdParty
              Version: 1
            OutputArtifacts:
              - Name: sourceCode
            Configuration:
              Owner: "prowe"
              Repo: "node-reference"
              Branch: master
              OAuthToken: !Ref RepoToken
        - Name: Build
          Actions:
          - Name: Build
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            InputArtifacts:
              - Name: sourceCode
            Configuration:
              ProjectName: !Ref BuildProject
            OutputArtifacts:
              - Name: buildResults
        - Name: Deploy_DEV
          Actions:
          - Name: Deploy
            RunOrder: 1
            RoleArn: !GetAtt PipelineRole.Arn
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: buildResults
            Configuration:
              StackName: ProductService
              ActionMode: REPLACE_ON_FAILURE
              TemplatePath: buildResults::cloudformation.template.yml
              TemplateConfiguration: buildResults::dev.params.json
              RoleArn: !GetAtt PipelineRole.Arn
              Capabilities: CAPABILITY_IAM
          - Name: IntegrationTest
            RunOrder: 2
            ActionTypeId:
              Category: Test
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            InputArtifacts:
              - Name: buildResults
            Configuration:
              ProjectName: !Ref IntegrationTest
