version: 0.2
env:
  variables: {}
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - export RELEASE_IMAGE_URL=$(cat RELEASE_IMAGE_URL.txt)
      - ls -l
  build:
    commands:
      - echo "About to exec $RELEASE_IMAGE_URL to $BASE_URL"
      - |
        docker run \
          -e BASE_URL=$BASE_URL \
          -e CLIENT_ID=$CLIENT_ID \
          -e ENCRYPTED_CLIENT_SECRET=$ENCRYPTED_CLIENT_SECRET \
          -e TOKEN_ENDPOINT=$TOKEN_ENDPOINT \
          $RELEASE_IMAGE_URL npm run integration-test